#!/bin/bash


chiminey_portal_container=`docker  ps  --filter "name=dockerchiminey_chiminey_1" | tail -n 1 | awk '{print $NF}' `


docker exec -ti $chiminey_portal_container python chiminey.py initial
